#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=Joey_Baseline
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:20:00
#SBATCH --mem=64000M
#SBATCH --output=../slurm/slurm_output_%A_training_test_single_gpu.out

module purge
module load 2019
module load Python/3.7.5-foss-2019b
module load CUDA/10.1.243
module load cuDNN/7.6.5.32-CUDA-10.1.243
module load NCCL/2.5.6-CUDA-10.1.243
module load Anaconda3/2018.12

# pip install --user --upgrade pip

cd ..

# Your job starts in the directory where you call sbatch
cd $HOME/joeynmt
pip install --user -r requirements.txt
pip install --user --editable .


# Activate your environment
# source activate ...
# Install things


# Run your code
srun python -m joeynmt train configs/transformer_iwslt14_deen_bpe_small_utility.yaml #