name: "iwslt14-deen-bpe-transformer_test"

data:
  src: "de"
  trg: "en"
  train: "test/data/iwslt14/train.bpe.32000"
  dev: "test/data/iwslt14/valid.bpe.32000"
  test: "test/data/iwslt14/test.bpe.32000"
  level: "bpe"
  lowercase: True
  max_sent_length: 62
  src_vocab: "test/data/iwslt14/vocab.txt"
  trg_vocab: "test/data/iwslt14/vocab.txt"

testing:
  beam_size: 1
  alpha: 1.0
  # LC-NMT specific things
  small_test_run: True
  mbr: True
  mbr_type: "editdistance"
  utility: "beer"
  num_samples: 3
  save_utility_per_sentence: False
training:
  load_model: "models/iwslt14-deen-bpe-transformer_test/1.ckpt"
  random_seed: 42
  optimizer: "adam"
  normalization: "tokens"
  adam_betas: [ 0.9, 0.999 ]
  scheduling: "plateau"
  patience: 5
  decrease_factor: 0.7
  loss: "crossentropy"
  learning_rate: 0.0003
  learning_rate_min: 0.00000001
  weight_decay: 0.0
  label_smoothing: 0
  batch_size: 128
  batch_type: "token"
  early_stopping_metric: "utility"
  epochs: 4
  validation_freq: 100
  logging_freq: 10
  eval_metric: "bleu"
  model_dir: "models/iwslt14-deen-bpe-transformer_test_checkpoint"
  overwrite: True
  shuffle: True
  use_cuda: True
  max_output_length: 10
  print_valid_sents: [ 0, 1, 2, 3, 4 ]
  save_latest_ckpt: True
  keep_last_ckpts: 5
 # LC-NMT specific things
  track_mbr: True
  mbr_type: "editdistance"
  utility: "beer"
  small_test_run: True
  utility_regularising: False
  utility_alpha: 1
  num_samples: 2
  ddp: True
  num_nodes: 1
  distributed_batch_sampler: True
  mean_baseline: True
  vimco_baseline: True
  wandb: True
  early_stopping: True
  early_stopping_patience: 10


model:
  initializer: "xavier"
  embed_initializer: "xavier"
  embed_init_gain: 1.0
  init_gain: 1.0
  bias_initializer: "zeros"
  tied_embeddings: True
  tied_softmax: True

  encoder:
    type: "transformer"
    num_layers: 1
    num_heads: 1
    embeddings:
      embedding_dim: 256
      scale: True
      dropout: 0.
    # typically ff_size = 4 x hidden_size
    hidden_size: 256
    ff_size: 1024
    dropout: 0.3
  decoder:
    type: "transformer"
    num_layers: 1
    num_heads: 1
    embeddings:
      embedding_dim: 256
      scale: True
      dropout: 0.
    # typically ff_size = 4 x hidden_size
    hidden_size: 256
    ff_size: 1024
    dropout: 0.3
